'use strict';

const mongoose = require('mongoose');

/**
 * Activity schema – stores each event received from the user_activities queue.
 * The `id` field carries the UUIDv4 generated by the API service, ensuring
 * idempotent upserts when a message is redelivered after a nack.
 */
const activitySchema = new mongoose.Schema(
    {
        id: {
            type: String,
            unique: true,
            required: true,
            index: true,
        },
        userId: {
            type: String,
            required: true,
            index: true,
        },
        eventType: {
            type: String,
            required: true,
        },
        timestamp: {
            type: Date,
            required: true,
        },
        processedAt: {
            type: Date,
            default: Date.now,
        },
        payload: {
            type: mongoose.Schema.Types.Mixed,
        },
    },
    {
        timestamps: true, // adds createdAt / updatedAt
        collection: 'activities',
    }
);

module.exports = mongoose.model('Activity', activitySchema);
